version: '2'

services:
  zk_seed:
    build:
      context: .
      dockerfile: ./docker/zookeeper.dockerfile
    container_name: zk_seed  # prevent scaling seed zk
    image: tipsi_zookeeper:latest

  zk:
    image: tipsi_zookeeper:latest
    environment:
      - ZK_SEED=zk_seed

  aiozk:
    build: .
    command: /bin/bash -c 'python3 setup.py install && nose2'
    depends_on:
      - zk
