version: '2'

services:
  zk:
    build:
      context: .
      dockerfile: ./docker/zookeeper.dockerfile

  aiozk:
    build: .
    command: /bin/bash -c 'python3 setup.py install && nose2'
    depends_on:
      - zk
